DROP TABLE IF EXISTS burger;
DROP TABLE IF EXISTS extras;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS menu;
DROP TABLE IF EXISTS drink;


CREATE TABLE burger (
id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
mustard BINARY NOT NULL,
mayonnaise BINARY NOT NULL,
ketchup BINARY NOT NULL,
meat VARCHAR(255) NOT NULL,
extraid INT NOT NULL);

CREATE TABLE extras (
id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
name VARCHAR(255) NOT NULL,
count INT NOT NULL);

CREATE TABLE users (
id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
username VARCHAR(45) NOT NULL,
password VARCHAR(255) NOT NULL);

CREATE TABLE menu (
userid INT NOT NULL,
burgerid INT NOT NULL,
drinkid INT NOT NULL);

CREATE TABLE drink (
id INT AUTO_INCREMENT NOT NULL PRIMARY KEY);

ALTER TABLE burger ADD CONSTRAINT burger_extraid_extras_id FOREIGN KEY (extraid) REFERENCES extras(id);
ALTER TABLE menu ADD CONSTRAINT menu_userid_users_id FOREIGN KEY (userid) REFERENCES users(id);
ALTER TABLE menu ADD CONSTRAINT menu_burgerid_burger_id FOREIGN KEY (burgerid) REFERENCES burger(id);
ALTER TABLE menu ADD CONSTRAINT menu_drinkid_drink_id FOREIGN KEY (drinkid) REFERENCES drink(id);
